### ISSUE TITLE
Wled on HOOBS/Homebridge

### ISSUE THREAD

**Issue by wildman199** [jstrausd/homebridge-simple-wled#1]
The requested accessory "WLED" was not registered by any plugin.
10/26/2020, 1:16:24 AM Your config.json is requesting the accessory "WLED" which has not been published by any installed 

how do I fix this

**Comment by jstrausd** [comment]
Can you send the section of the WLED accessory in the config.json?
Did you restart your HOOBS - Server after installing the plugin?
Can you confirm that the plugin was installed correctly without any issues?
