### ISSUE TITLE
Great job - preset sugestion

### ISSUE THREAD

**Issue by straubus** [jstrausd/homebridge-simple-wled#10]
Great job with this plugin! 
I have two questions: how to change colors in effects via HomeKit?
And have You thought about adding presets instead of effects?

**Comment by jstrausd** [comment]
Thanks.
How do you mean "change colors in effects"?
No i didn't, but i will have a look to it.

**Comment by xdwarf** [comment]
I would LOVE to be able to use presets too instead of the effects...

**Comment by straubus** [comment]
> Thanks.
> How do you mean "change colors in effects"?
> No i didn't, but i will have a look to it.

I mean, when I choose specific effects in HomeKit, I'd like to change colors of it. For example blue and purple in "blink" effect, I only managed to choose one of it. Have You got any advice? 

I am very looking for ability to assign presets instead of effects. It would give me more customization using wled app.

**Comment by jstrausd** [comment]
Ok, i will have a look to it. 
I will add this feature in the future.
