### ISSUE TITLE
add a homekit

### ISSUE THREAD

**Issue by denis86111** [jstrausd/homebridge-simple-wled#11]
hello, after the update, the lamp disappeared in the homekit and cannot be added.

**Comment by jstrausd** [comment]
From which to which update? 

Try renaming your WLED(s) to another name and restart your homebridge and try again.

**Comment by denis86111** [comment]
> С какого обновления?
> 
> Попробуйте переименовать WLED на другое имя, перезапустите домашний мост и повторите попытку.

Не помогает
![Uploading F7D0156E-6DCC-4C8C-B57D-31A07AB7F89C.png…]()

**Comment by denis86111** [comment]
what is the code when adding a homekit?
![Uploading 4B731973-8E71-439E-B626-1B757BE066CD.png…]()

**Comment by denis86111** [comment]
figured out, it was necessary to add a new accessory to the homekit with the homebridge code) thanks for the great plugin!

**Comment by j4k3** [comment]
@denis86111 I have the same problem, how did you solve yours?
