### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by recom273** [jstrausd/homebridge-simple-wled#12]
Can you take a look at this, I am getting polling errors - It's down to my lack of understanding, im feeling a bit thick at today - I have them both working individually.

```
{
            "platform": "WLED",
            "wleds": [
                {
                    "name": "Pixel Cube WLED",
                    "host": "192.168.1.172",
                    "log": true
                },
                {
                    "name": "Server Cab WLED",
                    "host": "192.168.168.107",
                    "effects": [
                        "solid",
                        "blink"
                    ],
                    "log": true
                }
            ]
        }
```

In the server cab, I have a temperature sensor, when the heat hits a number, then flashes red - if then switched back to solid, will that return to the regular solid cool blue. Am I on the right lines or is this beyond the plugin?

**Comment by jstrausd** [comment]
Hello, sorry for the late answer.... I was quite busy.
Can you send the error and can you exactly explain what your will is to do. (How do you realize this action when the temperature sensor hits the "temperature" to blink and so on?)

**Comment by recom273** [comment]
Hmm .. I too have been busy, I set up both again using same config and they were fine.

With regard to the temperature sensor, an aqara zigbee sensor - I need to have a look again, im pretty sure its more of a home app automation. Forget about it, I will apply myself when I have a little more time.
