### ISSUE TITLE
Devices no longer appear in Homekit

### ISSUE THREAD

**Issue by j4k3** [jstrausd/homebridge-simple-wled#13]
I've just updated to the newest version of homebridge-simple-wled, 1.2.3. I've changed my configuration according to the documentation. My three WLED devices are no no longer visible on any of my controller devices, they have disappeared from all Home apps. They are, however, still listed in the web UI.

What am I doing wrong?

    "platforms": [
        {
            "platform": "WLED",
            "wleds": [
                {
                    "name": "Schreibtisch",
                    "host": "192.168.178.59",
                    "effects": [
                        "Rainbow"
                    ]
                },
                {
                    "name": "Lowboard",
                    "host": "192.168.178.58",
                    "effects": [
                        "Rainbow"
                    ]
                },
                {
                    "name": "Sideboard",
                    "host": "192.168.178.31",
                    "effects": [
                        "Rainbow"
                    ]
                }
            ]
        },
        ...
    ]

**Comment by jstrausd** [comment]
You have to add the accessory manually via the plus icon on the top right in the home app and then you have to click at the bottom, to enter the code manually. In the next step you can select your device and as code you have to use the Homebridge code.

I hope this will help you.

**Comment by j4k3** [comment]
No, the homebridge itself is already connected and the three configured devices have also showed up previously. They disappeared the second I started the home app for the first time after the update.

**Comment by jstrausd** [comment]
try renaming the accessories and than restart the Homebridge.
