### ISSUE TITLE
update crashed my HOOBS hub

### ISSUE THREAD

**Issue by wildman199** [jstrausd/homebridge-simple-wled#15]

**Comment by wildman199** [comment]
After updating the simple wled all the json config setting are all out of order.  Had to do a system restore.

**Comment by jstrausd** [comment]
From which to which version did you update and what happend exactly after the update?
Is everything working now after the system restore?

**Comment by wildman199** [comment]
Restore fixed it. Didn’t have time to get details.

**Comment by wildman199** [comment]
From 1.0.14

**Comment by jstrausd** [comment]
Oh ok...
The big change from 1.0.14 to the latest version (currently 1.2.3) is, that the Plugin changed from the AccessoryPlugin to a Platform Accessory Plugin so you have to change your config.json to "platforms". See the Readme example (https://github.com/jstrausd/homebridge-simple-wled#-adding-the-accessory-to-the-configjson).

**Comment by wildman199** [comment]
Ok. Do I do the update first or the config and what is the benefit of new configuration?

**Comment by jstrausd** [comment]
It doesn't matter in which order you do it.
The benefits are, that you can control multiple wleds with one accessory and you can define a own list with effects you can control and so on...
