### ISSUE TITLE
How to. change default effects

### ISSUE THREAD

**Issue by Ron0815** [jstrausd/homebridge-simple-wled#18]
Hi, I just tried to preset some effects.  But the preference remains on the effect "rainbow runner", although the alteration I made was saved in the json-config.  What do I have to do to change that? Another point: There is no possibilty/menue in the home-app to select any of these effects. So, where can I find a presslection of the effects in homekit?
Could someone help? Best regards

**Comment by jstrausd** [comment]
Can you send the wled-section in the config.json and which version you are currently using?

**Comment by Ron0815** [comment]
Hi,
the config is:

   {
            "accessory": "WLED",
            "name": "WLED Garage 2",
            "host": "192.168.xxx.xx",
            "effects": [
                "Solid",
                "Spots"
            ],
            "log": true
        }

The version seems to be the newest v0.0.1

Best regards, Ron

**Comment by jstrausd** [comment]
Okay please update to the newest homebridge-simple-wled Plugin version (https://www.npmjs.com/package/homebridge-simple-wled) v.1.2.3.
Then you also have to change your config.json to something like:
https://github.com/jstrausd/homebridge-simple-wled#-adding-the-accessory-to-the-configjson

Do you also get any errors in the homebridge-console or in the logs?

**Comment by Ron0815** [comment]
Thanks for Your prompt help. I'll test that.

**Comment by Ron0815** [comment]
Now I had problems with the update. So I deinstalled and insralled again the latest version as You've recommended. But now WLED doesn't appear any,ore in homekit after restart of homebridge. The protocol tells me 
"The dynamic platform WLED from the plugin homebridge-simple-wled seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!"

What can I do now? 

My config is this:

        {
            "platform": "WLED",
            "name": "WLED Garage 1",
            "host": "192.168.178.130",
            "effects": [
                "Solid",
                "Spots"
            ]
        },
        {
            "platform": "WLED",
            "name": "WLED Garage 2",
            "host": "192.168.178.131",
            "effects": [
                "Solid",
                "Spots"
            ]
        }
    ],
    
Best regards, Ron

**Comment by jstrausd** [comment]
Please read through the README.md of the plugin. And look at the link posted above. There is an example of adding a WLED-instance in the README!

**Comment by Ron0815** [comment]
Sorry, again no result. I configured this:

        {
            "platform": "WLED",
            "name": "WLED Garage 1",
            "host": "192.168.xxx.xx",
            "effects": [
                "Solid",
                "Spots"
            ]
        },
        {
            "platform": "WLED",
            "wleds": [
                {
                    "name": "WLED Garage 1",
                    "host": "192.168.xxx.yy",
                    "effects": [
                        "Solid",
                        "Spots"
                    ],
                    "turnOffWledWithEffect": true
                },
                {
                    "name": "WLED Garage 2",
                    "host": "192.168.178.131",
                    "effects": [
                        "Solid",
                        "Spots"
                    ],
                    "turnOffWledWithEffect": true
                }
            ]
        }
    ],

But no WLED-button occurs in homekit. And again there is this red hint in the protocol:

"The dynamic platform WLED from the plugin homebridge-simple-wled seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!"

**Comment by jstrausd** [comment]
Are you on the latest homebridge version?
Do it show the device, if you click on the plus (+) in the HomeKit App and select "Add a new device" --> and then select you do not have a Code... ?

**Comment by Ron0815** [comment]
Thank You very much for Your help. Now the devices appear properly in homekit. I think we can close that issue. Best regards Ron
