### ISSUE TITLE
Effects support

### ISSUE THREAD

**Issue by sergoo-lbt** [jstrausd/homebridge-simple-wled#2]
Is it possible to add support for WLED effects? Let's say in the form of changing the HDMI outputs of the TV?
![4525CC11-2AC0-49E5-B2C2-F2B9FFDCF50B](https://user-images.githubusercontent.com/64399012/97780153-b3334400-1ba4-11eb-8d17-f55ecd27ec50.jpeg)

**Comment by jstrausd** [comment]
Yeah more effects are added soon. 
The plugin is currently only in "Beta", so it isn't completed and bug free yet.

Which app do you currently use to change the effects (On your screenshot)

**Comment by sergoo-lbt** [comment]
> Yeah more effects are added soon.
> The plugin is currently only in "Beta", so it isn't completed and bug free yet.
> 
> Which app do you currently use to change the effects (On your screenshot)

If there are effects, this plugin will have no equal! Screenshot from this article
https://sprut.ai/client/article/2760

**Comment by jstrausd** [comment]
> > Yeah more effects are added soon.
> > The plugin is currently only in "Beta", so it isn't completed and bug free yet.
> > Which app do you currently use to change the effects (On your screenshot)
> 
> If there are effects, this plugin will have no equal! Screenshot from this article
> https://sprut.ai/client/article/2760

Oh ok, this is already a HomeKit Plugin. 
So what do you want the plugin to do that it should be able to do?

**Comment by sergoo-lbt** [comment]
> > > Yeah more effects are added soon.
> > > The plugin is currently only in "Beta", so it isn't completed and bug free yet.
> > > Which app do you currently use to change the effects (On your screenshot)
> > 
> > 
> > If there are effects, this plugin will have no equal! Screenshot from this article
> > https://sprut.ai/client/article/2760
> 
> Oh ok, this is already a HomeKit Plugin.
> So what do you want the plugin to do that it should be able to do?

What is in the video from the link I gave is achieved using NodeRed. I would like the homebridge plugin to also be able to change effects. Is it possible?

**Comment by jstrausd** [comment]
Yes i can work on this. But it will take some time. 
Before adding new effects, i have to fix some other bugs.

**Comment by sergoo-lbt** [comment]
> Yes i can work on this. But it will take some time.
> Before adding new effects, i have to fix some other bugs.

This is great news! I'm looking forward to it! I wish you success!

**Comment by recom273** [comment]
thanks for your work on this - wled has been missing from homebridge - the current effect implementation is cool, with individual switches - that way we can integrate it with security system or motion sensors.

**Comment by djashjones** [comment]
How about this for an idea instead of having a full list of all available effects, a comma separated list of your favourite effects?

**Comment by recom273** [comment]
Any chance of multiple switches for multiple effects - great update btw

**Comment by jstrausd** [comment]
I still have to see how and if this is possible at Homebridge. But I'll take a closer look at it this week.
Btw. thanks for your donation: D

**Comment by jstrausd** [comment]
I published a new version...
Now you can configure a own list with effects and use it like on the screenshot above.

!! INFO !!
The Plugin is now a Platform-Plugin and has to be moved to the "platforms"-section in the config.json. (See the examples)

If you have any questions, feel free to ask....

**Comment by recom273** [comment]
So, when we add the the device through + > add accessory > "I dont have a code or cannot scan" > then add the tile .. It requests an 8 figure setup code, correct?

**Comment by sergoo-lbt** [comment]
> I published a new version...
> Now you can configure a own list with effects and use it like on the screenshot above.
> 
> !! INFO !!
> The Plugin is now a Platform-Plugin and has to be moved to the "platforms"-section in the config.json. (See the examples)
> 
> If you have any questions, feel free to ask....

You're just super cool! Your work is done perfectly! Be happy!

**Comment by djashjones** [comment]
Better than Home Assistant's version

**Comment by RomanGz** [comment]
Any particular reason you have the effects statically defined in `getAllEffects()`? Perhaps just grab them from the `/json/effects` endpoint...? I run the WLED audio reactive fork, and they have their own added effects.

**Comment by jstrausd** [comment]
@RomanGz Oh no... It was just provisional. (because i didn't wanted to request the effects everytime.. at the beginning) 
But i will add the "feature" to grab them from the JSON-API and cache them, to not use unnecessary bandwidth.

**Comment by jstrausd** [comment]
Ok I tried to fetch the effects dynamically, but it is very difficult due the fact I can only fetch it asynchronously...
So I have to find a perfect solution for this, but for now the static defined effects will do it...

**Comment by jstrausd** [comment]
Also I changed the config.json layout with the new version 1.1.1
Now you can add multiple WLED instances with the new dynamically platform plugin.

**Comment by RomanGz** [comment]
> Ok I tried to fetch the effects dynamically, but it is very difficult due the fact I can only fetch it asynchronously...
> 
> So I have to find a perfect solution for this, but for now the static defined effects will do it...

Haha. I tried myself after I asked and had the same problem with async. Wasted a whole day on it. Tried with axios & request. I may revisit it soon. Thanks for trying.

**Comment by sergoo-lbt** [comment]
> Also I changed the config.json layout with the new version 1.1.1
> Now you can add multiple WLED instances with the new dynamically platform plugin.

I am very interested, is it possible to add several separate tapes with one accessory?😅🙏🏻

**Comment by jstrausd** [comment]
@sergoo-lbt So you mean you can control multiple WLED-Strips with one HomeKit accessory?

**Comment by sergoo-lbt** [comment]
> So you mean you can control multiple WLED-Strips with one HomeKit accessory?

I ask, is it possible? I currently manage three wleds with a single homekit accessory using native wled synchronization. But this does not work very reliably. I would like to be able to group them into one honekit accessory, but this is not possible since they contain a piece of the TV))

**Comment by jstrausd** [comment]
Ok, yes i could add an option, to configure the host/s as a list and then you can simple control your devices with one HomeKit accessory.

**Comment by sergoo-lbt** [comment]
> Ok, yes i could add an option, to configure the host/s as a list and then you can simple control your devices with one HomeKit accessory.

This is incredible! I will look forward to it!🙏🏻🔥

**Comment by jstrausd** [comment]
@sergoo-lbt  In the new version (1.2.1) I added the option to control multiple WLED-hosts with one accessory.
For further infos check the README.md

**Comment by sergoo-lbt** [comment]
> @sergoo-lbt In the new version (1.2.1) I added the option to control multiple WLED-hosts with one accessory.
> For further infos check the README.md

I updated the plugin. You've done an incredible job! Right now, one accessory controls my three wleds, but there is a small problem with the accessory status. When I turn off the backlight with the brightness slider, after a few seconds, the accessory in homekit turns on again, while the LEDs themselves remain off!

**Comment by Batyushin** [comment]
In order not to get lost, a list of all effects. Choose who needs what.

"effects": [
	"Solid",
	"Blink",
	"Breathe",
	"Wipe",
	"Wipe Random",
	"Random Colors",
	"Sweep",
	"Dynamic",
	"Colorloop",
	"Rainbow",
	"Scan",
	"Dual Scan",
	"Fade",
	"Theater",
	"Theater Rainbow",
	"Running",
	"Saw",
	"Twinkle",
	"Dissolve",
	"Dissolve Rnd",
	"Sparkle",
	"Sparkle Dark",
	"Sparkle+",
	"Strobe",
	"Strobe Rainbow",
	"Strobe Mega",
	"Blink Rainbow",
	"Android",
	"Chase",
	"Chase Random",
	"Chase Rainbow",
	"Chase Flash",
	"Chase Flash Rnd",
	"Rainbow Runner",
	"Colorful",
	"Traffic Light",
	"Sweep Random",
	"Running 2",
	"Aurora",
	"Stream",
	"Scanner",
	"Lighthouse",
	"Fireworks",
	"Rain",
	"Merry Christmas",
	"Fire Flicker",
	"Gradient",
	"Loading",
	"Police",
	"Police All",
	"Two Dots",
	"Two Areas",
	"Circus",
	"Halloween",
	"Tri Chase",
	"Tri Wipe",
	"Tri Fade",
	"Lightning",
	"ICU",
	"Multi Comet",
	"Scanner Dual",
	"Stream 2",
	"Oscillate",
	"Pride 2015",
	"Juggle",
	"Palette",
	"Fire 2012",
	"Colorwaves",
	"BPM",
	"Fill Noise",
	"Noise 1",
	"Noise 2",
	"Noise 3",
	"Noise 4",
	"Colortwinkles",
	"Lake",
	"Meteor",
	"Meteor Smooth",
	"Railway",
	"Ripple",
	"Twinklefox",
	"Twinklecat",
	"Halloween Eyes",
	"Solid Pattern",
	"Solid Pattern Tri",
	"Spots",
	"Spots Fade",
	"Glitter",
	"Candle",
	"Fireworks Starburst",
	"Fireworks 1D",
	"Bouncing Balls",
	"Sinelon",
	"Sinelon Dual",
	"Sinelon Rainbow",
	"Popcorn",
	"Drip",
	"Plasma",
	"Percent",
	"Ripple Rainbow",
	"Heartbeat",
	"Pacifica",
	"Candle Multi",
	"Solid Glitter",
	"Sunrise",
	"Phased",
	"TwinkleUp",
	"Noise Pal",
	"Sine",
	"Phased Noise",
	"Flow",
	"Chunchun",
	"Dancing Shadows",
	"Washing machine",
	"Candy Cane",
	"Blends",
	"TV Simulator",
	"Dynamic Smooth"
]

**Comment by jstrausd** [comment]
@sergoo-lbt I released a new version, where this problem should be fixed.
