### ISSUE TITLE
WLED-Device not recognized

### ISSUE THREAD

**Issue by Ron0815** [jstrausd/homebridge-simple-wled#22]
After deleting a WLED device from Homekit due to a problem, I wanted to reintegrate it into Homekit. Unfortunately, the device is no longer recognized when I try to add it manually in Homekit. What can I do to solve the problem? Thx for any help!

**Comment by jstrausd** [comment]
You can try to rename your Wled device in the config --> restart your Homebridge and then try again

**Comment by Ron0815** [comment]
Okay, that‘s it. Thx for Your help!
    	Best regards
    
  

 Von: Jonathan Strauss ***@***.***>Gesendet: Donnerstag, Juni 17, 2021 7:36 PMAn: jstrausd/homebridge-simple-wledCc: Ron0815; AuthorBetreff: Re: [jstrausd/homebridge-simple-wled] WLED-Device not recognized (#22) 
You can try to rename your Wled device in the config --> restart your Homebridge and then try again
