### ISSUE TITLE
Device not showing in HomeKit

### ISSUE THREAD

**Issue by TristanGrahn** [jstrausd/homebridge-simple-wled#26]
The device is shown under "Accessory's" in home-bridge where I can control the brightness and effects, however it is not showing in the HomeKit app

**Comment by MarkARushton** [comment]
Did you have any luck with this? I’m facing the same issue

**Comment by TristanGrahn** [comment]
Hey yes so once you have it working, you can check using the assecorys in homebridge. Then go to the plug-in and plug-in in options then bridge the plug-in  and a we code will pop up and then scan that in HomeKit and the device will pop up

Best Regards Tristan

Student Number
219012853<tel:219012853>
Email Address
***@***.******@***.***>
Student Contact
0795888529<tel:0795888529>
Academic Year
2021
Qualification
B6ELSQ - BEng in Electrical & Electronic Eng
Offering Type
VT - APK CAMPUS FULL-TIME
Block
0 - YEAR BLOCK
Period of Study
2 - SECOND YEAR

On 03 Oct 2021, at 03:11, Mark ***@***.***> wrote:

﻿

Did you have any luck with this? I’m facing the same issue
