### ISSUE TITLE
No HB logs?

### ISSUE THREAD

**Issue by recom273** [jstrausd/homebridge-simple-wled#3]
Not really an issue .. but an observation - no log appears in the hb terminal when there is an action or activity - any plans to change this?

**Comment by jstrausd** [comment]
I will add a debug-option in the config.json, for the accessory to log infos into the HB-Terminal, in the next version.

**Comment by jstrausd** [comment]
@recom273 the feature for logging is now available in the new version of the plugin.

**Comment by recom273** [comment]
Great, thanks for your hardwork - I was using another plugin but it was just a simple colour and switch, this is a great way to integrate into homekit. Thanks.
