### ISSUE TITLE
not-an-issue :-) Forked your plugin, added a switch for "Live Override"

### ISSUE THREAD

**Issue by Bene2103** [jstrausd/homebridge-simple-wled#30]
Hi,

as you might know I forked your project and my goal was to add an extra switch, to switch between ambilight and moodlight.
So without knowledge in typescript but with programming experience I managed to get a switch and also the status update of the switch working.

I'd like to do an PR to your project, but when I prepare this PR it shows me "...can be automatically merged". I don't want to do this because if you want to use it, it shouldn't be automatically be merged. I think you should take a look at it and review my code. As I told you my typescript knowledge is pretty low.

Also i'am pretty new in using GitHub for code, can I do this PR without problems?

Heres a little background :-) I use an TV-Receiver with Linux on it and some software like BobLight to recreate the Ambilight effect. My WLED is connected to the Receiver via USB and "Adalight" but I wanted also to have a Moodlight without the need of another LED-strip. So with my changes I can switch between the two.

Thank you for this awesome plugin!

**Comment by jstrausd** [comment]
Hey, just open a new Pull Request and it should do this automatically without problems.
But nice for bringing into your own features :) It's great to see, that this plugin is used and maintained not just only by me.

**Comment by csupi003** [comment]
Hi @Bene2103 ! That's the feature I was looking for. I would love to test it.

**Comment by Bene2103** [comment]
Hey @jstrausd looks like we're not the only ones using your plugin ;-)

So i will do an PR but I think this will take some time.
Also in the past I've tried the plugin with multiple IP-Adresses/Devices and its works also as its meant to be.

In the meantime @csupi003 you can just fork my repo locally and build on your own, but I wouldn't recommend this method!

I don't recommend to do this. If you want this feature please wait until the PR is trough and then update via npm.

Otherwise if you just want to do this, just execute this via ssh or the way you interact with your instance:
`sudo npm uninstall homebridge-simple-wled`
`git clone https://github.com/Bene2103/homebridge-simple-wled.git`
`cd homebridge-simple-wled`
`sudo npm run build`
`sudo npm link`

restart homebridge and the plugin should be visible, just add '   "AmbilightSwitch": true   ' without '' to your config and your're good to go, otherwise go to my GitHub page. sudo is maybe necessary I don't know how you run your homebridge instance. 

If you get any errors while running "nom run bild" just google them, there you'll find the answers. Mostly its because some depencies are missing during building the code.

Let me know what you're thinking :-)

**Comment by Bene2103** [comment]
Alrighty, I've done the PR lets see how it goes :-)

**Comment by jstrausd** [comment]
I merged Pull Request into my project. 
I will publish tomorrow the new version on NPM.

**Comment by jstrausd** [comment]
The new version 1.3.0 with the ambilight added is now online on npmjs.org!
