### ISSUE TITLE
Error while polling WLED since version 1.3.0

### ISSUE THREAD

**Issue by AlexKusnezov** [jstrausd/homebridge-simple-wled#32]
Hey, after updating to 1.3.0 I’m getting error while polling on all of my WLED lights. Can you maybe look into it?

edit:for now reverting back to 1.2.4 solved my problem

**Comment by jstrausd** [comment]
Hey,
sorry for that, it seems like that this is a generic problem.

To fix this problem temporary, do not upgrade to 1.3.0 and stay at the last version 1.2.4!

I will fix the problem as soon as possible.

**Comment by v0r73x** [comment]
Hi jstrausd,
I see following error in log - might be help ? thx and happy new year :) 
![image](https://user-images.githubusercontent.com/48632087/148543595-b015b9dd-992e-4310-b7fe-b7f0d85e2960.png)

**Comment by jstrausd** [comment]
I just released version 1.3.1 with some bug fixes. 

- It fixes the issue that the brightness changes shortly to 100% after changing the brigthness
- It fixes the error described above (Error while polling WLED)
- And some small changes in package.json (dependencies)

**Comment by v0r73x** [comment]
issue with 100% is fixed - i like it :) thx 
now, just figure out why with homepod voice the color change changes to red instead of the spoken color and this plugin is solid state :)

**Comment by jstrausd** [comment]
Ok weird, on my HomePod mini it is changing the color correctly🧐

**Comment by v0r73x** [comment]
I guess I know the issue - I am using SR WLED and not the original one - on Alexa they return the right colors but on with plugin on homebridge it just switch to red or to black (out). Could be that there is something different in code? If you have an addidtional esp around you you can test it. I guess it will be same on your side.

**Comment by jstrausd** [comment]
Ok, Can you post your setup? (Microcontroller, WLED Version, Light Strip "Version")
But it could be that HomeKit is interpreting the color different.
Does this issue also occur with the Home App on an iPhone or Siri on iPhone?

**Comment by v0r73x** [comment]
amazing ! - if I do it by Iphone it works ! so forget my theorie I had before ;) 

so its just with the homepod...thanks for the hint to figure this out. But is it then related to the OS of homepod ?

**Comment by jstrausd** [comment]
Ok that's kinda good :D
Do u use a HomePod mini or just the original normal HomePod?

**Comment by v0r73x** [comment]
Homepod mini I use - and on ATV4 the homekit server is running (all in same network)

**Comment by jstrausd** [comment]
Do you use the latest version of Homebridge and for the HomePod mini?

**Comment by v0r73x** [comment]
jepp

**Comment by jstrausd** [comment]
Ok that's very very weird, that this issue occurs. The only way to fix this is to find out how your homepod is interpreting the colors and sending it to the Homebridge Plugin🧐

**Comment by v0r73x** [comment]
will give it a try - thx and have a n1ce evening

**Comment by v0r73x** [comment]
https://github.com/jstrausd/homebridge-simple-wled/issues/21#issuecomment-1023949286 its fixed with Homepod mini OS 15.3
