### ISSUE TITLE
Presets as Effect Switch in HomeKit

### ISSUE THREAD

**Issue by derpate1989** [jstrausd/homebridge-simple-wled#34]
Hallo,

I have set many preset with my favorite Color, brightness and Effect Speed. 

It is possible to integrate the self made preset as effect switch in HomeKit? 

Best regards

**Comment by ddcreation** [comment]
Duplicate of https://github.com/jstrausd/homebridge-simple-wled/issues/16, maybe we can close this one?

**Comment by mkormendy** [comment]
This can be closed.
