### ISSUE TITLE
1.3.2 Error when device not reachable

### ISSUE THREAD

**Issue by Bene2103** [jstrausd/homebridge-simple-wled#35]
Hi jstrausd,

I've got an issue with your latest version. I have a WLED device on my pc monitor which is most of the time offline. Your latest update crashed Homebridge because of the device being offline. Maybe you can take a look into this?

<img width="1421" alt="Bildschirmfoto 2022-01-17 um 23 01 04" src="https://user-images.githubusercontent.com/46553509/149841518-1ffd55de-ae8b-48be-b699-46f0570fa3de.png">

Just tried it to be sure, when device is powered on everything is working as expected.

Thank you!

**Comment by seppelicous** [comment]
Same issue here! When WLED is offline (no power), Homebridge is crashing continuously. I went back to 1.3.1

**Comment by jstrausd** [comment]
I released a new version, where this issue should be fixed.

**Comment by seppelicous** [comment]
1.3.3 works now fine for me!
