### ISSUE TITLE
I can't see Wled in the Home App

### ISSUE THREAD

**Issue by Damianod27** [jstrausd/homebridge-simple-wled#41]
Hello. I connected the first WLED today. I have properly configured the config.json file. After Homebridge reboot, the device appeared in the Accessories tab. It can be easily controlled. However, it does not appear in the Home Application. I tried to use it as a slave bridge as well. The Wled Bridge has been added to the Home Application without any problems, but the accessory is still not visible. The control also works via WWW and WLED applications for iOS.What could be the problem? I have been using Homebridge for several years and haven't had this problem yet. I do not know if it matters but I am using ESP8266 and Led 2811 - 12V.

![1](https://user-images.githubusercontent.com/79320859/160027885-661bb3ea-87b0-46ed-a787-c1599f147c57.png)
![2](https://user-images.githubusercontent.com/79320859/160027891-5fdaf23d-a9c2-4651-b516-0bcbcecb33d3.png)
![3](https://user-images.githubusercontent.com/79320859/160027893-9938b0f1-bb4f-4bc2-be67-408e47d366d3.png)
![4](https://user-images.githubusercontent.com/79320859/160027896-03b5b651-2628-4684-927b-7598f78f230d.png)
![5](https://user-images.githubusercontent.com/79320859/160027897-cc96c695-9dff-463f-8abb-358dc0e33b3f.png)
.

**Comment by eXCepT74** [comment]
Hello - what was the reason -  i have same problem :(((
