### ISSUE TITLE
Preset function ? 

### ISSUE THREAD

**Issue by Damianod27** [jstrausd/homebridge-simple-wled#42]
Hello.  Thanks for Your plugin.  Are you planning to add Preset functionality to the Home App.  I think that is one of the most important things that would come in handy.  It would be possible to change the designed lighting scenes.

**Comment by Danos0100** [comment]
I absolutely second this. This would allow saving a combination of effect + effect parameters + colour palette in order to enable this later. Please consider adding presets to the plugin! :)

**Comment by ddcreation** [comment]
Duplicate of [https://github.com/jstrausd/homebridge-simple-wled/issues/34](https://github.com/jstrausd/homebridge-simple-wled/issues/34). Maybe we can close this one?

**Comment by mkormendy** [comment]
This can be closed.
