### ISSUE TITLE
WLED recognized as a TV

### ISSUE THREAD

**Issue by AdictiK5** [jstrausd/homebridge-simple-wled#47]
Hello

I installed WLED on several ESPs and everything works fine with HomeKit thanks to this Plugin for HomeBridge.

However, I have a problem, my WLEDs are recognized as "TVs" in HomeKit.
When I say to Siri "Turn on the TV", she asks me "In which rooms?" (because all WLEDs are represented as TVs).
If I answer "the living room", Siri turns on the TV and WLED.

It's not blocking but annoying and not very practical...
Do you have any solution to fix this problem?

Thank you in advance for your help.

PS: I also use the Harmony Plugin for Home Bridge, I don't know if that can influence or not.

**Comment by jstrausd** [comment]
Hello, for disabling the Effect Switch, which is displayed as TV Control you can pass the `"showEffectControl": true` parameter to the device config. 
But the TV is for now the best solution to display the effects. I'm looking forward to find a other solution.
