### ISSUE TITLE
Donate button

### ISSUE THREAD

**Issue by recom273** [jstrausd/homebridge-simple-wled#5]
If you put a button on your homebridge plugin tab, I might be inclined to buy you a coffee here and there.

I like the work you are doing, there is another plugin that isn't really in development - maybe the odd donation will give you some incentive to keep on going.

**Comment by jstrausd** [comment]
Thank you for wanting to support me and for being so interested in the plugin. I have now linked a PayPal donation button at the bottom of the README.md. I am happy about every donation and will do my best to permanently develop the plugin and keep it up to date.
Thanks for your support <3
