### ISSUE TITLE
Configure own Effect-Switch issue

### ISSUE THREAD

**Issue by Poldou** [jstrausd/homebridge-simple-wled#6]
Hello, first, your pluggin is so cool, thanks for that.
I have an issue when I want to add another effect to my pluggin, this make homebridge crash every time.
![Capture d’écran 2020-12-27 123102](https://user-images.githubusercontent.com/48698311/103169806-6b950580-483f-11eb-8a63-68e7cc0e7d6f.png)

**Comment by jstrausd** [comment]
Thanks,
Ok that looks very weird. Can you post your configuration for the WLED device?

**Comment by Poldou** [comment]
![Capture d’écran 2020-12-27 134415](https://user-images.githubusercontent.com/48698311/103171094-a7cd6380-4849-11eb-9a1e-b31054e61e21.png)

**Comment by jstrausd** [comment]
Can you try out a other Effect than Palette.
Because i think, that's an invalid effect name.

**Comment by Poldou** [comment]
Ok, so I have changed Twinkle for the effect Merry Christmas and it's works fine !
Thank's
