### ISSUE TITLE
Option to remove the effect switch

### ISSUE THREAD

**Issue by mabrodeur** [jstrausd/homebridge-simple-wled#7]
Hi,

Thanks for the plugin it works great!

Would there be a way (maybe a setting) to remove the effect switch and only have the light bulb?
I only use the light bulb accessory because I manage my effects directly in WLED and I use the plugin to turn on/off the lights.
I would like to remove that effect switch from my Home app.

Thanks!

**Comment by jstrausd** [comment]
Hey, thanks for using my plugin :D

Yes, I can add an option to disable the effect-switch.
I will be working on this option later this week.

**Comment by mabrodeur** [comment]
Wow, that's great ! 
Thanks for your work!

**Comment by jstrausd** [comment]
You are now able to add the option `disableEffectSwitch": true` to the specific accessory to disable the effect-switch.

**Comment by mabrodeur** [comment]
Works perfectly!
Thanks a lot again
