### ISSUE TITLE
Last update problem

### ISSUE THREAD

**Issue by burakcankose** [jstrausd/homebridge-simple-wled#9]
Hello, I'm having a problem after the last update. Every time I restart the homebridge, the current wled goes into no response state and a new wled homekit is ready to be added on. I did the editing as a new configuration, I restarted the device completely, but the problem was not solved. As far as I check from the logs, every time the homebridge restarts, it starts to work through different ports.

**Comment by sergoo-lbt** [comment]
> Здравствуйте, у меня возникла проблема после последнего обновления. Каждый раз, когда я перезапускаю домашний мост, текущий wled переходит в состояние без ответа, и новый домашний набор wled готов к добавлению. Я делал редактирование как новую конфигурацию, перезапустил устройство полностью, но проблема не была решена. Насколько я проверяю по логам, каждый раз при перезапуске homebridge начинает работать через разные порты.

Same problem. Confirm

**Comment by jstrausd** [comment]
I'm sorry for the circumstances, yesterday I released a new version where this problem has been fixed. Version 1.1.3

**Comment by burakcankose** [comment]
Hi, I did the new update but at this time the wled homekit stopped appearing in the add section.  Is this problem related to me?

**Comment by jstrausd** [comment]
@burakcankose Does any error appear in your Homebridge console?

**Comment by burakcankose** [comment]
no problem appears, the port where it finds the device and the working port is visible, but when I scan, I cannot see the device.  In the previous version, I see a new named device at every restart.

**Comment by jstrausd** [comment]
+

+#x47

**Comment by jstrausd** [comment]
Ok, try to rename your WLED devices to another name and restart your Homebridge and see if the problem still occurs.

**Comment by earlywaff** [comment]
> Ok, try to rename your WLED devices to another name and restart your Homebridge and see if the problem still occurs.

Yes. I have a problem.

**Comment by burakcankose** [comment]
> Ok, try to rename your WLED devices to another name and restart your Homebridge and see if the problem still occurs.

This is work for me. Thank you !

**Comment by jstrausd** [comment]
@earlywaff Which problem do you have?

**Comment by earlywaff** [comment]
<img width="1067" alt="Снимок экрана 2021-02-01 в 23 55 13" src="https://user-images.githubusercontent.com/59850734/106517001-f0330d80-64e8-11eb-8b98-2e1b7c6cf7fc.png">
I uninstalled the bridge, reinstalled the plugin, rebooted everything.
Renamed it.
Trying to add the bridge, it says wrong code.

**Comment by jstrausd** [comment]
Can you please send you config.json and are you using the latest version of homebridge-simple-wled?

**Comment by earlywaff** [comment]
{
            "platform": "WLED",
            "name": "VERHSHKAF",
            "host": "192.168.1.36",
            "log": true,
            "effects": [
                "Gradient",
                "Merry Christmas",
                "Blink",
                "Wipe",
                "Wipe Random",
                "Sweep",
                "Dynamic",
                "Colorloop",
                "Rainbow",
                "Scan",
                "Dual Scan",
                "Fireworks 1D",
                "Theater",
                "Theater Rainbow",
                "Saw",
                "Twinkle",
                "Running",
                "Rainbow Runner"
            ]
        },
        {
            "platform": "WLED",
            "name": "KOMOD",
            "host": "192.168.1.66",
            "log": true,
            "effects": [
                "Gradient",
                "Merry Christmas",
                "Blink",
                "Wipe",
                "Wipe Random",
                "Sweep",
                "Dynamic",
                "Colorloop",
                "Rainbow",
                "Scan",
                "Dual Scan",
                "Fireworks 1D",
                "Theater",
                "Theater Rainbow",
                "Saw",
                "Twinkle",
                "Running",
                "Rainbow Runner"
            ]
            
            1.2.1 version

**Comment by jstrausd** [comment]
Ok, I see the problem...
With the newer versions you have to add the WLEDs like the format below:

`    "platforms": [
        {
            "platform": "WLED",
            "wleds": [
                {
                    "name": "LED-Tisch",
                    "host": "10.0.0.52",
                    "effects": ["Rainbow Runner", "Circus"],
                    "log": true
                },
                {
                    "name": "LED-Kasten",
                    "host": ["10.0.0.53", "10.0.0.54"],
                    "effects": ["Rainbow Runner", "Circus"],
                }
            ]
        }
    ]`

**Comment by earlywaff** [comment]
Thank you very much, I'll fix it and report back!)

**Comment by earlywaff** [comment]
Yes, thank you very much for supporting this plugin, now I will try to make a donation!) The error was indeed in the config)

**Comment by jstrausd** [comment]
I'm glad that it works now and that you like the plugin :D

**Comment by v0r73x** [comment]
Hi, i have another issue since the update - when I try to change the color i get the following exception and the Homebridge crashes 

![image](https://user-images.githubusercontent.com/48632087/106708813-c87c9c00-65f3-11eb-8bf8-8c75178b57a2.png)

config is as follow:

![image](https://user-images.githubusercontent.com/48632087/106708970-0a0d4700-65f4-11eb-86e8-583612ff0292.png)

**Comment by jstrausd** [comment]
Ok i know the problem, i will fix it as fast as possible.

**Comment by jstrausd** [comment]
@v0r73x I released a new version, where this problem should be fixed.

**Comment by v0r73x** [comment]
wow - so fast ? I am appreciate :) will test immediantly :) 
btw: great work ;9

**Comment by jstrausd** [comment]
Ok thanks. 
Because this is now a Platform plugin, every accessory has it's own UUID to be identified and cached... and this number is also just a ID for the device. Because in a Platform plugin multiple accessories can be defined and also could be added dynamically by runtime.
So for example the plugin adds multiple accessories in runtime and the don't have a specific name you can identify them mostly with the Platform-Name and the ID.
I hope I could answer your question. :D
